/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import controle.ControleClienteJuridico;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelos.ClientesFisicos;
import modelos.ClientesJuridicos;

/**
 *
 * @author Kevin
 */
public class TelaClientePessoaJuridica extends javax.swing.JFrame {

    /**
     * Creates new form TelaClientePessoaJuridica
     */
    public TelaClientePessoaJuridica() {
        initComponents();
            jFormattedTextField1_CNPJ.setText("000000000000");
            jFormattedTextField1_CEP.setText("11111111111");
            jFormattedTextField1_Contato.setText("22222222222");
            jFormattedTextField1_InscricaoEstadual.setText("333333333333333");
            jFormattedTextField1_NomeFantasia.setText("Nome de Fantasia");
            jTextField1_Bairro.setText("Bairro");
            jTextField1_Cidade.setText("cidade");
            jTextField1_Email.setText("email@email");
            jTextField1_Endereco.setText("Endereco");
            jTextField1_Numero.setText("44");
            jTextField1_RazaoSocial.setText("Razao Social");
            jTextField1_UF.setText("GO");
    }

    TelaClientePessoaJuridica(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1_lbCNPJ = new javax.swing.JLabel();
        jLabel1_lbRazao = new javax.swing.JLabel();
        jTextField1_RazaoSocial = new javax.swing.JTextField();
        jLabel2_lbNomeFant = new javax.swing.JLabel();
        jFormattedTextField1_NomeFantasia = new javax.swing.JFormattedTextField();
        jFormattedTextField1_InscricaoEstadual = new javax.swing.JFormattedTextField();
        jLabel3_lbInscriEst = new javax.swing.JLabel();
        jLabel4_lbContato = new javax.swing.JLabel();
        jFormattedTextField1_Contato = new javax.swing.JFormattedTextField();
        jLabel1_lbEmail = new javax.swing.JLabel();
        jTextField1_Email = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextField1_CEP = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField1_Endereco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField1_Numero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField1_UF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField1_Bairro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField1_Cidade = new javax.swing.JTextField();
        jButton1_Cadastrar = new javax.swing.JButton();
        jButton1_Cancelar = new javax.swing.JButton();
        jFormattedTextField1_CNPJ = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CADASTRO CLIENTES JURIDICOS");
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel1_lbCNPJ.setText("CNPJ:");
        jPanel1.add(jLabel1_lbCNPJ);
        jLabel1_lbCNPJ.setBounds(23, 34, 51, 14);

        jLabel1_lbRazao.setText("Razao Social:");
        jPanel1.add(jLabel1_lbRazao);
        jLabel1_lbRazao.setBounds(370, 80, 81, 14);
        jPanel1.add(jTextField1_RazaoSocial);
        jTextField1_RazaoSocial.setBounds(460, 80, 190, 20);

        jLabel2_lbNomeFant.setText("Nome Fantasia:  ");
        jPanel1.add(jLabel2_lbNomeFant);
        jLabel2_lbNomeFant.setBounds(23, 84, 99, 14);
        jPanel1.add(jFormattedTextField1_NomeFantasia);
        jFormattedTextField1_NomeFantasia.setBounds(126, 81, 200, 20);

        try {
            jFormattedTextField1_InscricaoEstadual.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("############")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(jFormattedTextField1_InscricaoEstadual);
        jFormattedTextField1_InscricaoEstadual.setBounds(126, 146, 200, 20);

        jLabel3_lbInscriEst.setText("Incrição Estadual: ");
        jPanel1.add(jLabel3_lbInscriEst);
        jLabel3_lbInscriEst.setBounds(23, 149, 89, 14);

        jLabel4_lbContato.setText("Contato:");
        jPanel1.add(jLabel4_lbContato);
        jLabel4_lbContato.setBounds(390, 150, 63, 14);

        try {
            jFormattedTextField1_Contato.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(jFormattedTextField1_Contato);
        jFormattedTextField1_Contato.setBounds(460, 150, 140, 20);

        jLabel1_lbEmail.setText("E-mail:");
        jPanel1.add(jLabel1_lbEmail);
        jLabel1_lbEmail.setBounds(31, 193, 57, 14);

        jTextField1_Email.setText(" ");
        jPanel1.add(jTextField1_Email);
        jTextField1_Email.setBounds(92, 190, 260, 20);

        jLabel1.setText("CEP:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(390, 190, 44, 14);

        try {
            jFormattedTextField1_CEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(jFormattedTextField1_CEP);
        jFormattedTextField1_CEP.setBounds(461, 190, 140, 20);

        jLabel2.setText("Endereço:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(31, 247, 57, 14);

        jTextField1_Endereco.setText(" ");
        jPanel1.add(jTextField1_Endereco);
        jTextField1_Endereco.setBounds(92, 244, 260, 20);

        jLabel3.setText("Numero:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(387, 247, 44, 14);

        jTextField1_Numero.setText(" ");
        jPanel1.add(jTextField1_Numero);
        jTextField1_Numero.setBounds(435, 244, 64, 20);

        jLabel5.setText("UF:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(517, 247, 33, 14);

        jTextField1_UF.setText(" ");
        jPanel1.add(jTextField1_UF);
        jTextField1_UF.setBounds(554, 244, 47, 20);

        jLabel6.setText("Bairro:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 290, 39, 14);

        jTextField1_Bairro.setText(" ");
        jPanel1.add(jTextField1_Bairro);
        jTextField1_Bairro.setBounds(90, 290, 100, 20);

        jLabel7.setText("Cidade:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(220, 290, 46, 14);

        jTextField1_Cidade.setText(" ");
        jPanel1.add(jTextField1_Cidade);
        jTextField1_Cidade.setBounds(270, 290, 115, 20);

        jButton1_Cadastrar.setText("Cadastrar");
        jButton1_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_CadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1_Cadastrar);
        jButton1_Cadastrar.setBounds(70, 360, 102, 23);

        jButton1_Cancelar.setText("Cancelar");
        jButton1_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_CancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1_Cancelar);
        jButton1_Cancelar.setBounds(230, 360, 98, 23);

        try {
            jFormattedTextField1_CNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(jFormattedTextField1_CNPJ);
        jFormattedTextField1_CNPJ.setBounds(125, 40, 200, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_CadastrarActionPerformed
      try {
            ControleClienteJuridico conexao = ControleClienteJuridico.getInstance();
            
            String cnpj = jFormattedTextField1_CNPJ.getText();
            String endereco = jTextField1_Endereco.getText();
            String numero = jTextField1_Numero.getText();
            String bairro = jTextField1_Bairro.getText();
            String cidade = jTextField1_Cidade.getText();
            String uf = jTextField1_UF.getText();
            String cep = jFormattedTextField1_CEP.getText();
            String nomeFantasia = jFormattedTextField1_NomeFantasia.getText();
            String razaoSocial = jTextField1_RazaoSocial.getText();
            String inscricaoEstadual = jFormattedTextField1_InscricaoEstadual.getText();
            String email = jTextField1_Email.getText();
            String contato = jFormattedTextField1_Contato.getText();
            String id = "";
           

            
            ClientesJuridicos clienteJuridico = new ClientesJuridicos ( id, cnpj,  razaoSocial,  nomeFantasia,  inscricaoEstadual,  endereco,  numero,  bairro,  cidade,  uf,  cep,    email,  contato);
            
            conexao.incluirDadosPersistencia(clienteJuridico, 1);

            jFormattedTextField1_CNPJ.setText("");
            jFormattedTextField1_CEP.setText("");
            jFormattedTextField1_Contato.setText("");
            jFormattedTextField1_InscricaoEstadual.setText("");
            jFormattedTextField1_NomeFantasia.setText("");
            jTextField1_Bairro.setText("");
            jTextField1_Cidade.setText("");
            jTextField1_Email.setText("");
            jTextField1_Endereco.setText("");
            jTextField1_Numero.setText("");
            jTextField1_RazaoSocial.setText("");
            jTextField1_UF.setText("");
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jButton1_CadastrarActionPerformed

    private void jButton1_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_CancelarActionPerformed
       
           
        
        this.dispose();
    }//GEN-LAST:event_jButton1_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaClientePessoaJuridica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaClientePessoaJuridica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaClientePessoaJuridica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaClientePessoaJuridica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaClientePessoaJuridica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Cadastrar;
    private javax.swing.JButton jButton1_Cancelar;
    private javax.swing.JFormattedTextField jFormattedTextField1_CEP;
    private javax.swing.JFormattedTextField jFormattedTextField1_CNPJ;
    private javax.swing.JFormattedTextField jFormattedTextField1_Contato;
    private javax.swing.JFormattedTextField jFormattedTextField1_InscricaoEstadual;
    private javax.swing.JFormattedTextField jFormattedTextField1_NomeFantasia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_lbCNPJ;
    private javax.swing.JLabel jLabel1_lbEmail;
    private javax.swing.JLabel jLabel1_lbRazao;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2_lbNomeFant;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3_lbInscriEst;
    private javax.swing.JLabel jLabel4_lbContato;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1_Bairro;
    private javax.swing.JTextField jTextField1_Cidade;
    private javax.swing.JTextField jTextField1_Email;
    private javax.swing.JTextField jTextField1_Endereco;
    private javax.swing.JTextField jTextField1_Numero;
    private javax.swing.JTextField jTextField1_RazaoSocial;
    private javax.swing.JTextField jTextField1_UF;
    // End of variables declaration//GEN-END:variables
}
