/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Kevin
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1_Cadastros = new javax.swing.JMenu();
        jMenuItem1_CadastroClienteFisico = new javax.swing.JMenuItem();
        jMenuItem1_CadastroClienteJuridico = new javax.swing.JMenuItem();
        jMenuItem1_CadastrarMotorista = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2_Consulta = new javax.swing.JMenu();
        jMenuItem5_ConsultaClienteFisico = new javax.swing.JMenuItem();
        jMenuItem6_ConsultaClienteJuridico = new javax.swing.JMenuItem();
        jMenuItem7_ConsultaMotorista = new javax.swing.JMenuItem();
        jMenuItem8_ConsultaVeiculo = new javax.swing.JMenuItem();
        jMenuItem9_ConsultaModelo = new javax.swing.JMenuItem();
        jMenuItem10_ConsultaMarca = new javax.swing.JMenuItem();
        jMenuItem5_ConsultaContratos = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3_Contratos = new javax.swing.JMenu();
        jMenuItem1_Locacao = new javax.swing.JMenuItem();
        jMenuItem1_Venda = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Bem Vindo a\n\t JL : Rent a Car\n\n");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Escolha uma das opções no menu acima para começar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(jLabel2)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        jMenu1_Cadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-add-48.png"))); // NOI18N
        jMenu1_Cadastros.setText("Cadastros");

        jMenuItem1_CadastroClienteFisico.setText("Cliente Fisico");
        jMenuItem1_CadastroClienteFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_CadastroClienteFisicoActionPerformed(evt);
            }
        });
        jMenu1_Cadastros.add(jMenuItem1_CadastroClienteFisico);

        jMenuItem1_CadastroClienteJuridico.setText("Cliente Juridico");
        jMenuItem1_CadastroClienteJuridico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_CadastroClienteJuridicoActionPerformed(evt);
            }
        });
        jMenu1_Cadastros.add(jMenuItem1_CadastroClienteJuridico);

        jMenuItem1_CadastrarMotorista.setText("Motorista");
        jMenuItem1_CadastrarMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_CadastrarMotoristaActionPerformed(evt);
            }
        });
        jMenu1_Cadastros.add(jMenuItem1_CadastrarMotorista);

        jMenuItem2.setText("Veiculo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1_Cadastros.add(jMenuItem2);

        jMenuItem3.setText("Modelo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1_Cadastros.add(jMenuItem3);

        jMenuItem4.setText("Marca");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1_Cadastros.add(jMenuItem4);

        jMenuBar1.add(jMenu1_Cadastros);

        jMenu2_Consulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-edit-property-48.png"))); // NOI18N
        jMenu2_Consulta.setText("Consultas/Alteracoes");

        jMenuItem5_ConsultaClienteFisico.setText("Cliente Fisico");
        jMenuItem5_ConsultaClienteFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5_ConsultaClienteFisicoActionPerformed(evt);
            }
        });
        jMenu2_Consulta.add(jMenuItem5_ConsultaClienteFisico);

        jMenuItem6_ConsultaClienteJuridico.setText("Cliente Juridico");
        jMenuItem6_ConsultaClienteJuridico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6_ConsultaClienteJuridicoActionPerformed(evt);
            }
        });
        jMenu2_Consulta.add(jMenuItem6_ConsultaClienteJuridico);

        jMenuItem7_ConsultaMotorista.setText("Motorista");
        jMenuItem7_ConsultaMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7_ConsultaMotoristaActionPerformed(evt);
            }
        });
        jMenu2_Consulta.add(jMenuItem7_ConsultaMotorista);

        jMenuItem8_ConsultaVeiculo.setText("Veiculo");
        jMenuItem8_ConsultaVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8_ConsultaVeiculoActionPerformed(evt);
            }
        });
        jMenu2_Consulta.add(jMenuItem8_ConsultaVeiculo);

        jMenuItem9_ConsultaModelo.setText("Modelo");
        jMenuItem9_ConsultaModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9_ConsultaModeloActionPerformed(evt);
            }
        });
        jMenu2_Consulta.add(jMenuItem9_ConsultaModelo);

        jMenuItem10_ConsultaMarca.setText("Marca");
        jMenuItem10_ConsultaMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10_ConsultaMarcaActionPerformed(evt);
            }
        });
        jMenu2_Consulta.add(jMenuItem10_ConsultaMarca);

        jMenuItem5_ConsultaContratos.setText("Contratos de Vendas");
        jMenuItem5_ConsultaContratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5_ConsultaContratosActionPerformed(evt);
            }
        });
        jMenu2_Consulta.add(jMenuItem5_ConsultaContratos);

        jMenuItem1.setText("Contratos de Locação");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2_Consulta.add(jMenuItem1);

        jMenuBar1.add(jMenu2_Consulta);

        jMenu3_Contratos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-document-48.png"))); // NOI18N
        jMenu3_Contratos.setText("Contratos");

        jMenuItem1_Locacao.setText("Locacao");
        jMenuItem1_Locacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_LocacaoActionPerformed(evt);
            }
        });
        jMenu3_Contratos.add(jMenuItem1_Locacao);

        jMenuItem1_Venda.setText("Venda");
        jMenuItem1_Venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_VendaActionPerformed(evt);
            }
        });
        jMenu3_Contratos.add(jMenuItem1_Venda);

        jMenuBar1.add(jMenu3_Contratos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1_CadastrarMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_CadastrarMotoristaActionPerformed
                    new TelaMotorista().setVisible(true);
    }//GEN-LAST:event_jMenuItem1_CadastrarMotoristaActionPerformed

    private void jMenuItem1_CadastroClienteJuridicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_CadastroClienteJuridicoActionPerformed
new TelaClientePessoaJuridica().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1_CadastroClienteJuridicoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
new TelaVeiculo().setVisible(true);       

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
new TelaModelosCarro().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
new TelaMarca().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1_LocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_LocacaoActionPerformed
        try {
            new TelaLocacao().setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1_LocacaoActionPerformed

    private void jMenuItem1_VendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_VendaActionPerformed
new TelaVenda().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1_VendaActionPerformed

    private void jMenuItem6_ConsultaClienteJuridicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6_ConsultaClienteJuridicoActionPerformed
new TelaConsultaAlteracaoJuridico().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6_ConsultaClienteJuridicoActionPerformed

    private void jMenuItem5_ConsultaClienteFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5_ConsultaClienteFisicoActionPerformed
  new TelaConsultaAlteracaoFisico().setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5_ConsultaClienteFisicoActionPerformed

    private void jMenuItem7_ConsultaMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7_ConsultaMotoristaActionPerformed
new TelaConsultaAlteracaoMotorista().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7_ConsultaMotoristaActionPerformed

    private void jMenuItem8_ConsultaVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8_ConsultaVeiculoActionPerformed
new TelaConsultaAlteracaoVeiculos().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8_ConsultaVeiculoActionPerformed

    private void jMenuItem10_ConsultaMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10_ConsultaMarcaActionPerformed
new TelaConsultaAlteracaoMarcas().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10_ConsultaMarcaActionPerformed

    private void jMenuItem5_ConsultaContratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5_ConsultaContratosActionPerformed
new TelaConsultaAlteracaoContratoVenda().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5_ConsultaContratosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
new TelaConsultaAlteracaoLocacao().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem9_ConsultaModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9_ConsultaModeloActionPerformed
     new TelaConsultaAlteracaoModelosCarro().setVisible(true);
    }//GEN-LAST:event_jMenuItem9_ConsultaModeloActionPerformed

    private void jMenuItem1_CadastroClienteFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_CadastroClienteFisicoActionPerformed

        new TelaClienteFisicoo().setVisible(true);

    }//GEN-LAST:event_jMenuItem1_CadastroClienteFisicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu1_Cadastros;
    private javax.swing.JMenu jMenu2_Consulta;
    private javax.swing.JMenu jMenu3_Contratos;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10_ConsultaMarca;
    private javax.swing.JMenuItem jMenuItem1_CadastrarMotorista;
    private javax.swing.JMenuItem jMenuItem1_CadastroClienteFisico;
    private javax.swing.JMenuItem jMenuItem1_CadastroClienteJuridico;
    private javax.swing.JMenuItem jMenuItem1_Locacao;
    private javax.swing.JMenuItem jMenuItem1_Venda;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5_ConsultaClienteFisico;
    private javax.swing.JMenuItem jMenuItem5_ConsultaContratos;
    private javax.swing.JMenuItem jMenuItem6_ConsultaClienteJuridico;
    private javax.swing.JMenuItem jMenuItem7_ConsultaMotorista;
    private javax.swing.JMenuItem jMenuItem8_ConsultaVeiculo;
    private javax.swing.JMenuItem jMenuItem9_ConsultaModelo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
